### ISSUE TITLE
Firmware Recovery Tool crashes on OSX 14.6 Mojave

### ISSUE THREAD

**Issue by EspoTek** [EspoTek/Labrador#104]
Report from a user in the wild that the Firmware Recovery Tool is crashing on their Mac.

Looks like a `nullptr` dereference within libdfuprog.

**Comment by DavidPhillipOster** [comment]
I did two things to fix this as a user:

1.) I ran the app as an administrator from the command line with:
sudo Labrador.app/Contents/MacOS/Labrador

2) I put Labrador.app in /Applications.

Once it was properly initialized I can run the Labrador repeatedly by clicking on its icon, like any normal Mac app, no sudo needed.

A) So, I'm all set. You might consider updating your documentation in case other Mac users hit this.

B) You might consider using calls like NSBundle.mainBundle.bundleURL to get a file URL to the app, then use that to build resource URLs rather than assuming the app is in /Applications.
