### ISSUE TITLE
Labrador and Linux packaking standards

### ISSUE THREAD

**Issue by cyberl33t** [EspoTek/Labrador#114]
I'm currently making an Arch Linux package of labrador, and I have noticed some issues with it. The installer does not adhere to the Linux packaging standards very well:

1) The stuff in /firmware and /waveforms should really be installed in /usr/share/, while the Labrador executable should be kept in /usr/bin/, (or preferably just plain /usr/bin/labrador without the /usr/bin/labrador -> /usr/bin/EspoTek/Labrador symlink.) Now, if those files are moved to /usr/share, the program does not find them.

2) The builtin libusb library is completely unnecessary and should never be built on Linux. All distros already include libusb by default - actually qt5 itself depends on it.

3)  The files dfu-programmer.exe, flash.bat and wipe.bat in /firmware should never be installed on any other platforms than Windows. What those files are doing within Linux sources, anyway?

**Comment by EspoTek** [comment]
All 3 of your points are correct (although I do need to supply a libusb binary for the .AppImage).
The third one is especially embarrassing.

Unfortunately, fixing this up is not on my list of priorities at the moment as it doesn't affect function.  I'd be happy to accept a PR, but otherwise this can be left for now.
