### ISSUE TITLE
Suggestion: Extension

### ISSUE THREAD

**Issue by kapil-iitk** [EspoTek/Labrador#14]
It's a nice project. I can suggest you one thing, instead of USB you can use bluetooth module for the communication and interfacing with PC and android. This will also protect the device (PC or mobile) and the remote logging is possible.

**Comment by EspoTek** [comment]
Thanks, Kapril.  :)

I thought about using Bluetooth, but ended up deciding against it because it's more expensive, doesn't provide power, and most desktop PC users don't have Bluetooth installed.
The PC should be protected by PTC fuses in all but the most extreme cases (such as shorting 240V directly to the data lines or something like that).

Of course, you are right when you mention the advantages of Bluetooth, plus it would enable iOS compatibility too.
You could try and add it yourself if you want, but unfortunately all of the interfaces is designed around an assumption of constant streaming, which may cause battery life problems on a wireless device.
