### ISSUE TITLE
How to Connect Labrador to Computer

### ISSUE THREAD

**Issue by ddd15dd** [EspoTek/Labrador#153]
Hi, I am using a USB to microUSB cord to connect the labrador to my laptop, and the Red LED light lights up. But when I open the software it says Device Not Connected. For my circuits lab, it says that I should calibrate it before plugging the Labrador into the breadboard. But when I try to do that I get an error message "You need to connect the board before calibrating it!"

Please help!

**Comment by EspoTek** [comment]
Please see the troubleshooting guide here:
https://github.com/EspoTek/Labrador/wiki/Troubleshooting-Guide

The most common issue I hear about is caused by people using a USB cable without data lines.  When you use that same cable to connect a USB device (such as an Android phone) to your computer, is that device detected?
