### ISSUE TITLE
Duplication of Range Dialog

### ISSUE THREAD

**Issue by lkoepsel** [EspoTek/Labrador#165]
I like the idea of being able to set the Range Dialog default to automatically show. Unfortunately, when I do so on a Mac running Big Sur I get a two sets showing up. (See image) If necessary I can also test on Linux and Windows.

![doublerangeshown](https://user-images.githubusercontent.com/7906684/112723513-2b8c0000-8ecc-11eb-93b2-6c3829aba2b6.png)

If it's possible while fixing/looking into this issue, it would be great if you could also have the values remain defaulted. Currently they also show up approximately as Vmax = 2.5V, Vin = -500mV. Retaining the new values in between application launches would be great.

**Comment by EspoTek** [comment]
I have no idea why this appeared - I couldn't produce this behaviour on Windows.

Either way, I've just simplified the code that handles this dramatically so that only one `scopeRangeEnterDialog` object can exist at once.  It should fix the issue you were having - please let me know as I don't currently have access to a Mac for testing.

**Comment by lkoepsel** [comment]
Nice work! Its been fixed on the latest release.

It would be nice if it could save the values as well.
Thanks!
Lief
