### ISSUE TITLE
need to know how to

### ISSUE THREAD

**Issue by richSPI** [EspoTek/Labrador#193]
Hi Chris,
Bought the lab as a learning tool and so far it has been great.  Amazing amount of functionality but I want to really dig into the guts of it to understand how it works.
I would like to learn how to do the following:
1. determine what version of the firmware is in the device
2. compile the firmware so I can change parts to see the impact of the changes
3. compile the desktop version with the same intent.

I know these are big topics so I was hoping you could point me some directions.
Just curious, are you working on updates to labrador or other projects like labrador?
thankful for any help,
jrs

**Comment by EspoTek** [comment]
Hi mate.  Thanks for both your support and your kind words!

Really great to see people curious about the internals of this!

Check the "Building from Source" section of the readme for compilation instructions.
https://github.com/EspoTek/Labrador

Regarding the firmware version in the device, the version on the board is tied directly to the host software it's communicating with (as in, if the board's firmware is different to the version expected by the software, it will be overwritten immediately).

See EXPECTED_FIRMWARE_VERSION and DEFINED_EXPECTED_VARIANT in genericusbdriver.h.

In addition to the version, there is the variant.  This defines how the isochronous communications take place.  On 64-bit Windows, there are 6x 128 byte endpoints, on all other platforms there is a single 1023 byte endpoint.  This is due to overlapping limitations with the Atmel USB hardware as well as the host driver.  On 64-bit Windows, LibusbK will synchronise endpoints properly; on other platforms we can't do this.

Also see this, if you're curious:
https://docs.google.com/document/d/1ZDO1RTarQTNB6Pdfi_T4YukL51oYan_kk_teb1cu6-o/edit?usp=sharing

As for other projects, Labrador is still being updated occasionally, but nothing else at the moment.
Have gone into full on provider-dad mode since having a kid and am focused 100% on what I know will provide financially.
Specifically, an eBay store specialising in used video games, with operations turbo-charged by some custom Python scripts (not open-sourced!):
https://www.ebay.com.au/usr/56bits
