### ISSUE TITLE
Recording - where is this?

### ISSUE THREAD

**Issue by rvjohnson70** [EspoTek/Labrador#244]
I see in closed issue #12 reference to record and snapshot functions. In the latest version (EspoTek_Labrador-2cc0678-x86_64) I can find the snapshot function under the File menu, but where can I find record?

**Comment by EspoTek** [comment]
The record feature was rerolled into a more generic DAQ mode.

You can use File->DAQ Settings to configure it, then File->Enable DAQ to start a recording.

The new DAQ mode allows you to use sample averaging to reduce the amount of data written to disk.  For example, if you wanted to, you could get it to write one measurement to disk every 30 seconds, rather than 750,000 per second.
