### ISSUE TITLE
Documentation (pinout) queries

### ISSUE THREAD

**Issue by DeeJay** [EspoTek/Labrador#39]
(Related to issue #38 New Pinout, but that has been closed.)

The present (diagram) version of the pinout documentation seems to differ from the previous annotated photo version. I have tried to work out the truth by trial and error, but I am getting confused...

In particular:

The oscilloscope channel locations are reversed.

The Digital Output pins are numbered in different directions.

The Signal Generator channels are labelled in different directions.

The Logic Analyser channels are both marked Channel 1.

The use of the Power Supply jumper is not clear. I assume the Power Supply output from the system is presented in the centre pin on the 3-way header, and the jumper is needed to link it to the final header or breadboard? Is the other orientation of the jumper simply a parking place to store the jumper if the output is isolated?

The calibration routine calls for connections to be made to the usb connector. Are the two Ground locations on the board (next to the Power Supply output, and adjacent to the 3v3 header) at the same dc signal level as the usb shield, and can they be used as substitutes?

**Comment by EspoTek** [comment]
Sorry about that.
No idea how I managed to make 4 mistakes at once.

Here is the new (fixed) diagram:
![pinout](https://user-images.githubusercontent.com/22040436/37638753-89b99496-2c62-11e8-83dd-38fd253beee5.png)

The jumper acts as a switch.  Top 2 pins are "off".  Bottom 2 are "on".  The reason there's a jumper rather than a mechanical switch is because some of the power supply feedback circuit is broken out (see Power Supply Expansion Header), allowing you to dramatically increase the maximum power output through use of an expansion board (which does not exist yet).

The two grounds are both at the same level as the usb shield and can be used as substitutes.  On-board polyfuses are at the high rails (PC-side they are usually at GND).
