### ISSUE TITLE
Scope XY mode plots in wrong order

### ISSUE THREAD

**Issue by emlyn** [EspoTek/Labrador#90]
It looks like in XY mode, the points are plotted in order of increasing X instead of in the order they were captured, leading to the plot getting "filled in" with almost-vertical lines:
![image](https://user-images.githubusercontent.com/405237/60176797-40c38e80-980f-11e9-98a9-c138c26ae44a.png)

**Comment by EspoTek** [comment]
Thanks for the bug report.  Definitely looks like you're right.  Will get onto this ASAP.

**Comment by Gernreich** [comment]
Yep saw the same thing when I was making Lissajous figures

**Comment by EspoTek** [comment]
![Screenshot_20190630_130235](https://user-images.githubusercontent.com/22040436/60391683-7af69e00-9b37-11e9-8400-65a1396c4233.png)

Fixed in 0b007c4.
I was using a "QCPGraph" rather than a "QCPCurve".

As a side note, you can increase the exposure time of the X-Y mode by holding CTRL and scrolling out.  This is a side-effect of the way the plots are made, but it works great.

**Comment by Gernreich** [comment]
Very cool 😁 thanks!
